# Spring 애플리케이션 설정
spring:
  application:
    name: kakaoLogin  # dating과 kakaoLogin 중 택일. kakaoLogin 유지

  # 데이터베이스 설정 (Oracle)
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe  # orcl이 아니라 XE로 통일
    username: system
    password: "1111"

  # JPA Hibernate 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle12cDialect

  # Thymeleaf 설정
  thymeleaf:
    cache: false

  # Spring Security 설정
  security:
    user:
      name: spring@tjoeun.com
      password: 321654987
    oauth2:
      client:
        registration:
          google:
            client-id: 1056048942789-40nk06kub9ra1lun52juvmnloinkbmej.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-id: 8e5de6e501057a2da53448b44b2928da
            client-secret: Edq8FlqZ59mrJbOBNXNcgetcCzP00eaL
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # 서버 포트 설정
  server:
    port: 8080

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

# 로그 설정 (Hibernate SQL 로깅)
logging:
  level:
    org.hibernate.type.descriptor.sql: trace

# 파일 저장 경로 설정
itemImgLocation: C:/mall/itemImages
uploadPath: file:///C:/mall/

# 네이버 API 설정
naver:
  client:
    id: cggTG11yuhthBsh6HqYo
    secret: r8sLlFN3af
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
